# Generated by Django 2.0.2 on 2018-08-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redmine_host', models.CharField(max_length=255)),
                ('redmine_port', models.CharField(max_length=255)),
                ('redmine_api_access_key', models.CharField(max_length=100)),
                ('imap_email_client_host', models.CharField(max_length=255)),
                ('imap_email_client_port', models.PositiveIntegerField()),
                ('email_login', models.CharField(max_length=255)),
                ('email_password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
