# Generated by Django 2.0.2 on 2018-08-14 18:10

import bugtracker_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0002_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='redmine_host',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='redmine_port',
        ),
        migrations.AddField(
            model_name='setting',
            name='redmine_email',
            field=models.EmailField(default='redmine@exaple.com', max_length=254),
        ),
        migrations.AddField(
            model_name='setting',
            name='redmine_url',
            field=models.CharField(default='http://locahost:3000', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='regex_to_parse_email',
            field=models.TextField(default='-{40}.+Status: (?P<status>\\w+).+-{40}(?P<description>.+)-{2}(?si)'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(default=bugtracker_app.models.IssueStatus(1, 'new'), on_delete=django.db.models.deletion.PROTECT, to='bugtracker_app.IssueStatus'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='imap_email_client_port',
            field=models.PositiveIntegerField(default=993),
        ),
    ]
