# Generated by Django 2.0.2 on 2018-08-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0003_auto_20180814_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='imap_email_client_host',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='imap_email_client_port',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='redmine_email',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='regex_to_parse_email',
        ),
        migrations.AddField(
            model_name='setting',
            name='project_id',
            field=models.CharField(default='the_matrix', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='smtp_email_client_host',
            field=models.CharField(default='smtp.gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='smtp_email_client_port',
            field=models.PositiveIntegerField(default=465),
        ),
    ]
