# Generated by Django 2.0.2 on 2018-08-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0004_auto_20180816_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='body',
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(default='ffsdfvs fdfbgfrsd dfd'),
            preserve_default=False,
        ),
    ]
