# Generated by Django 2.0.2 on 2018-08-17 16:52

import bugtracker_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0005_auto_20180816_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(default=bugtracker_app.models.IssueStatus(1, 'новая'), on_delete=django.db.models.deletion.PROTECT, to='bugtracker_app.IssueStatus'),
        ),
    ]
