# Generated by Django 2.1 on 2018-08-20 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0007_issue_notify_by_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bugtracker_app.IssueCategory'),
            preserve_default=False,
        ),
    ]
