# Generated by Django 2.1 on 2018-08-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0007_issue_notify_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='redmine_sync_every_mins',
            field=models.PositiveSmallIntegerField(default=720, help_text='Как часто будет происходить синхронизация с redmine'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
