# Generated by Django 2.1 on 2018-08-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0008_auto_20180820_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='redmine_sync_every_mins',
            field=models.PositiveSmallIntegerField(default=720),
            preserve_default=False,
        ),
    ]
