# Generated by Django 2.1 on 2018-08-28 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0009_auto_20180819_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='imap_email_client_host',
            field=models.CharField(default='smtp.gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='imap_email_client_port',
            field=models.PositiveIntegerField(default=465),
        ),
    ]
