# Generated by Django 2.1 on 2018-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0009_setting_redmine_sync_every_mins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='redmine_sync_every_mins',
            field=models.PositiveSmallIntegerField(default=720, help_text='как часто будет просходить синхронизация (обновление данных) с redmine'),
        ),
    ]
