# Generated by Django 2.1 on 2018-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0010_auto_20180820_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='email_body_pattern',
            field=models.TextField(default='\nЗдравствуйте, {user}!\nСтатус вашей ошибки "{issue_subject}" был изменён с "{issue_status_old}" на "{issue_status_new}".\n--\nС уважением, команда разработчиков Россельхознадзора.\n', help_text='Шаблон письма, который будет использоваться для отправки письма.'),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_subject_pattern',
            field=models.CharField(default='Статус ошибки {issue_id} изменён', help_text='Шаблон темы письма, который будет использоваться для отправки письма.', max_length=100),
        ),
    ]
