# Generated by Django 2.1 on 2018-08-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0010_auto_20180828_1635'),
        ('bugtracker_app', '0011_auto_20180820_1155'),
    ]

    operations = [
    ]
