# Generated by Django 2.1 on 2018-08-30 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker_app', '0012_merge_20180829_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='email_body_pattern',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='email_subject_pattern',
        ),
        migrations.AddField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='imap_email_client_host',
            field=models.CharField(default='imap.google.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='setting',
            name='imap_email_client_port',
            field=models.PositiveIntegerField(default=993),
        ),
    ]
