# Generated by Django 2.1 on 2018-08-30 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0014_auto_20180830_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('support_user', models.CharField(blank=True, max_length=255, null=True)),
                ('end_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker_app.Issue')),
            ],
        ),
    ]
