# Generated by Django 2.1 on 2018-09-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0016_auto_20180830_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuecomment',
            name='end_user_email',
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
