# Generated by Django 2.1 on 2018-09-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0017_auto_20180917_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuecomment',
            old_name='support_user',
            new_name='from_username',
        ),
    ]
