# Generated by Django 2.1 on 2018-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0019_issuecomment_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
