# Generated by Django 2.1 on 2018-09-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0020_auto_20180918_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
