# Generated by Django 2.1 on 2018-09-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0021_auto_20180918_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='bugtracker_app.Issue'),
        ),
    ]
