# Generated by Django 2.1 on 2018-09-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0022_auto_20180918_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='bugtracker_app.Issue'),
        ),
    ]
