# Generated by Django 2.1 on 2018-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0023_auto_20180918_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='note_from_issue_author',
            field=models.TextField(default='\n=========================\nКомментарий автора заявки\n=========================\n', help_text='Заголовок комментария который отобразится в redmine'),
        ),
    ]
