# Generated by Django 2.1.1 on 2018-10-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0024_setting_note_from_issue_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='comment_mail_template',
            field=models.TextField(default='\nДоброго времени суток, {user_name}!\nНа одну из ваших заявок был оставлен комментарий.\nВы можете посмотреть её по ссылке {issue_url}.\n--\nC уважением, служба поддержки {company_name}.\n', help_text='Этот шаблон отправится клиенту на email, когда ему будет оставлен комментарий.'),
        ),
        migrations.AddField(
            model_name='setting',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='note_from_issue_author',
            field=models.TextField(default='\n+=========================+\n+Комментарий автора заявки+\n+=========================+\n\n', help_text='Заголовок комментария который отобразится в redmine'),
        ),
    ]
