# Generated by Django 2.1.1 on 2018-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0025_auto_20181001_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='comment_mail_template',
            field=models.TextField(default='\nДоброго времени суток, {user_name}!\nНа одну из ваших заявок был оставлен комментарий.\nСодержание комментария:\n"{comment_content}".\nВы можете посмотреть её по ссылке {issue_url}.\n--\nC уважением, служба поддержки {company_name}.\n', help_text='Этот шаблон отправится клиенту на email, когда ему будет оставлен комментарий.'),
        ),
    ]
