# Generated by Django 2.1.1 on 2018-10-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0027_issuecomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='error_after_report_template',
            field=models.TextField(default='\nДоброго времени суток!\nНа сайте произошла ошибка, когда пользователь\nпытался отправить заявку об ошибке.\nИнформация об инциденте:\n-id пользователя: {user}\n-время возникновения: {time}\n-сообщение ошибки: {error_message}\n--\nПроверьте соединение с Redmine.\n', help_text='Этот шаблон отправится админу на email, \n        если на сайте произойдёт ошибка отправки заявки.'),
        ),
    ]
