# Generated by Django 2.1.1 on 2018-10-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0029_auto_20181003_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(help_text='Дата выхода версии', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bugtracker_app.IssueVersion'),
        ),
    ]
